#logging:
#   pattern:
#    console: "%d - %msg%n"
#   file: /var/log/tomcat/sell.log
#  level:
#    com.gwh.LoggerTest: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.92.129/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true #打印SQL

server:
  servlet:
    context-path: /sell
